/* Generated By:JavaCC: Do not edit this line. SelectorParserConstants.java */
using System;
namespace CodeStreet.Selector.Parser
{
	
	public struct SelectorParserConstants_Fields{
		public readonly static int EOF = 0;
		public readonly static int TK_TRUE = 5;
		public readonly static int TK_FALSE = 6;
		public readonly static int TK_NULL = 7;
		public readonly static int TK_OR = 8;
		public readonly static int TK_AND = 9;
		public readonly static int TK_NOT = 10;
		public readonly static int TK_BETWEEN = 11;
		public readonly static int TK_LIKE = 12;
		public readonly static int TK_IN = 13;
		public readonly static int TK_IS = 14;
		public readonly static int TK_ESCAPE = 15;
		public readonly static int TK_MINUS = 16;
		public readonly static int TK_PLUS = 17;
		public readonly static int TK_MULT = 18;
		public readonly static int TK_DIV = 19;
		public readonly static int TK_EQ = 20;
		public readonly static int TK_NE = 21;
		public readonly static int TK_GT = 22;
		public readonly static int TK_GE = 23;
		public readonly static int TK_LT = 24;
		public readonly static int TK_LE = 25;
		public readonly static int TK_LPAREN = 26;
		public readonly static int TK_RPAREN = 27;
		public readonly static int TK_SEMICOLON = 28;
		public readonly static int TK_COMMA = 29;
		public readonly static int TK_LONG = 30;
		public readonly static int TK_DOUBLE = 31;
		public readonly static int TK_FLOAT = 32;
		public readonly static int TK_STRING = 33;
		public readonly static int TK_IDENTIFIER = 34;
		public readonly static int TK_LETTER = 35;
		public readonly static int TK_DIGIT = 36;
		public readonly static int DEFAULT = 0;
		public readonly static System.String[] tokenImage = new System.String[]{"<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"TRUE\"", "\"FALSE\"", "\"NULL\"", "\"OR\"", "\"AND\"", "\"NOT\"", "\"BETWEEN\"", "\"LIKE\"", "\"IN\"", "\"IS\"", "\"ESCAPE\"", "\"-\"", "\"+\"", "\"*\"", "\"/\"", "\"=\"", "\"<>\"", "\">\"", "\">=\"", "\"<\"", "\"<=\"", "\"(\"", "\")\"", "\";\"", "\",\"", "<TK_LONG>", "<TK_DOUBLE>", "<TK_FLOAT>", "<TK_STRING>", "<TK_IDENTIFIER>", "<TK_LETTER>", "<TK_DIGIT>"};
	}
	public interface SelectorParserConstants
	{
		//UPGRADE_NOTE: Members of interface 'SelectorParserConstants' were extracted into structure 'SelectorParserConstants_Fields'. 'ms-help://MS.VSCC.2003/commoner/redir/redirect.htm?keyword="jlca1045_3"'
		
	}
}